backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "recipes"
    label: "Recipes"
    folder: "recipes"
    extension: "yaml"
    create: true
    path: "{{title}}/index"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Category", name: "category", widget: "list", min: 1 }
      - label: "Ingredients"
        name: "description"
        widget: "list"
        field: { label: "Item", name: "item", widget: "string" }
      - label: "Directions"
        name: "directions"
        widget: "list"
        field: { label: "Instr", name: "instr", widget: "string" }
